#Save do OOP Clicker
#Fri Jun 26 10:04:02 GMT-03:00 2026
autoclick=13
classe_abstrata=0
classe_basica=0
estagiario=0
framework_proprio=0
heranca_simples=0
instancias=2115
interface=0
polimorfismo=0
upgrade_autoclick_1=true
upgrade_autoclick_2=true
upgrade_autoclick_3=true
upgrade_classe_abstrata_1=false
upgrade_classe_abstrata_2=false
upgrade_classe_abstrata_3=false
upgrade_classe_basica_1=true
upgrade_classe_basica_2=true
upgrade_classe_basica_3=true
upgrade_click_1=true
upgrade_click_2=false
upgrade_click_3=false
upgrade_critico_1=true
upgrade_critico_2=true
upgrade_critico_3=true
upgrade_estagiario_1=true
upgrade_estagiario_2=true
upgrade_estagiario_3=true
upgrade_framework_proprio_1=false
upgrade_framework_proprio_2=false
upgrade_framework_proprio_3=false
upgrade_heranca_simples_1=false
upgrade_heranca_simples_2=false
upgrade_heranca_simples_3=false
upgrade_interface_1=false
upgrade_interface_2=false
upgrade_interface_3=false
upgrade_polimorfismo_1=false
upgrade_polimorfismo_2=false
upgrade_polimorfismo_3=false
