#Save do OOP Clicker
#Fri Jun 19 16:29:33 GMT-03:00 2026
autoclick=1
classe_abstrata=2
classe_basica=3
estagiario=2
framework_proprio=1
heranca_simples=2
instancias=3961772
interface=2
polimorfismo=3
upgrade_autoclick_1=true
upgrade_autoclick_2=true
upgrade_autoclick_3=true
upgrade_classe_basica_1=true
upgrade_classe_basica_2=true
upgrade_classe_basica_3=true
upgrade_clique_1=true
upgrade_clique_2=true
upgrade_clique_3=true
upgrade_critico_1=true
upgrade_critico_2=true
upgrade_critico_3=true
upgrade_estagiario_1=true
upgrade_estagiario_2=true
upgrade_estagiario_3=true
